<?php
/**
 * @file
 * Code for the Feature coop tournoi feature.
 */

include_once 'feature_coop_tournoi.features.inc';

/**
 * Implements hook_node_view().
 */
function feature_coop_tournoi_node_view($node, $view_mode, $langcode) {
  //dpm($node);
  if ($node->type == 'tournoi_two') {

    $settings = field_extra_fields_get_display('node', $node->type, $view_mode);
    if($settings["extra_field_inscrits"]['visible']){
      $node->content["extra_field_inscrits"] = array(
        "#markup" => views_embed_view('liste_des_inscrits', 'liste_inscrits'),//list_registrations_page($node->type, $node),//views_embed_view('products', 'attachment_4'),
      );
    }
  }
  if ($node->type == 'tournoi_three') {

    $settings = field_extra_fields_get_display('node', $node->type, $view_mode);
    if($settings["extra_field_inscrits"]['visible']){
      $node->content["extra_field_inscrits"] = array(
        "#markup" => views_embed_view('liste_des_inscrits', 'liste_inscrits'),//list_registrations_page($node->type, $node),//views_embed_view('products', 'attachment_4'),
      );
    }
  }
}

/**
 * Implements hook_field_extra_fields().
 */
function feature_coop_tournoi_field_extra_fields() {
  $extra['node']['tournoi_two'] = array(
    'display' => array(
      'extra_field_inscrits' => array(
        'label' => t('inscrits (extra)'),
        'weight' => 0,
      ),
    )
  );
  $extra['node']['tournoi_three'] = array(
    'display' => array(
      'extra_field_inscrits' => array(
        'label' => t('inscrits (extra)'),
        'weight' => 0,
      ),
    )
  );

  return $extra;
}

